In [21]:
import geopandas as gpd
import numpy as np
import os
import pandas as pd
import pyreadstat as prs
import re

from IPython.display import display, HTML
from pathlib import Path

import config as c

In [22]:
print(c.drg)
for f in sorted(os.listdir(c.drg)):
    print(f)

../DRG
DRG316July.sps
DRG_Wave3_16July.csv
USAID DRG Wave 3_16July.sav

In [40]:
drgSav = os.path.join(c.drg, 'USAID DRG Wave 3_16July.sav')
df, meta = prs.read_sav(drgSav)

print('{}'.format('-'*40))
#print(df.info())
#print('{}'.format('-'*40))
print('Rows: {}  Cols: {}'.format(df.shape[0], df.shape[1]))
#pd.set_option('display.expand_frame_repr', False)
#print(df.head())
#print(display(HTML(df.head(5).to_html())))
dfAdmins = df[['region', 'munic']]
print(display(HTML(dfAdmins.head(10).to_html())))

col_names = meta.column_names
col_labels = meta.column_labels
col_names_labels = dict(zip(col_names, col_labels))
print('Names: {}  Labels: {}'.format(len(col_names), len(col_labels)))
i = 1
# for name, label in col_names_labels.items():
#     unique_cnt = len(df[name].unique())
#     print('{:<3} {:<5} {:<10}  {}'.format(i, unique_cnt, name, label))
#     i+=1

print('{}'.format('-'*40))
# i = 1
# vvl_dict = meta.variable_value_labels
# for k1, v1 in vvl_dict.items():
#     if not k1.lower() in ['region', 'munic']:
#         continue
#     print('\n({}) Code: {}\nQuestion: {}\nvalue type: {})'.format(i, k1, col_names_labels[k1], type(v1)))
#     for k2, v2 in v1.items():
#         print('    {}  {}'.format(k2, v2))
#     i+=1

----------------------------------------
Rows: 2270  Cols: 250

None
Names: 250  Labels: 250
----------------------------------------

In [55]:
print(meta.variable_value_labels['region'])
rDict = meta.variable_value_labels['region']
pd.DataFrame.from_dict({'Region': rDict})
dfRegion = pd.DataFrame(list(rDict.items()), index=list(rDict.keys()), columns=['RCode', 'RName'])
print(display(HTML(dfRegion.head(10).to_html())))

print(meta.variable_value_labels['munic'])
rDict = meta.variable_value_labels['munic']
pd.DataFrame.from_dict({'Munic': rDict})
dfMunic = pd.DataFrame(list(rDict.items()), index=list(rDict.keys()), columns=['MCode', 'MName'])
print(display(HTML(dfMunic.head(80).to_html())))

{1.0: 'Tbilisi', 2.0: 'Kakheti', 3.0: 'Kvemo Kartili', 4.0: 'Shida Kartli', 5.0: 'Samckhe-Djavakheti', 6.0: 'Adjara', 7.0: 'Guria', 8.0: 'Samegrelo-Zemo svaneti', 9.0: 'Imereti-kvemo svaneti', 10.0: 'Mckheta-Mtianeti'}

None
{1.0: 'Mtatsminda', 2.0: 'Vake', 3.0: 'Saburtalo', 4.0: 'Krtsanisi', 5.0: 'Isani', 6.0: 'Samgori', 7.0: 'Chugureti', 8.0: 'Didube', 9.0: 'Nadzaladevi', 10.0: 'Gldani', 11.0: 'Sagarejo', 12.0: 'Gurjaani', 13.0: 'Sighnaghi', 14.0: 'Dedoplistskaro', 15.0: 'Sighnaghi', 16.0: 'Kvareli', 17.0: 'Lagodekhi', 18.0: 'Kvareli', 19.0: 'Telavi', 20.0: 'Kvareli', 21.0: 'Telavi', 22.0: 'Akhmeta', 23.0: 'Rustavi', 24.0: 'Gardabani', 25.0: 'Tetritskaro', 26.0: 'Bolnisi', 27.0: 'Dmanisi', 28.0: 'Tsalka', 29.0: 'Dmanisi', 30.0: 'Marneuli', 31.0: 'Mtskheta', 32.0: 'Dusheti', 33.0: 'Tianeti', 34.0: 'Dusheti', 35.0: 'Kaspi', 36.0: 'Kareli', 37.0: 'Gori', 38.0: 'Khashuri', 39.0: 'Adigeni', 40.0: 'Akhaltsikhe', 41.0: 'Aspindza', 42.0: 'Borjomi', 43.0: 'Akhalkalaki', 44.0: 'Ninotsminda', 45.0: 'Akhalkalaki', 46.0: 'Kutaisi', 47.0: 'Tkibuli', 48.0: 'Terjola', 49.0: 'Kharagauli', 50.0: 'Baghdati', 51.0: 'Kharagauli', 52.0: 'Zestaphoni', 53.0: 'Sachkhere', 54.0: 'Khoni', 55.0: 'Vani', 56.0: 'Samtredia', 57.0: 'Chiatura', 58.0: 'Tskaltubo', 59.0: 'Mestia', 60.0: 'Oni', 61.0: 'Ambrolauri', 62.0: 'Ozurgeti', 63.0: 'Chokhatauri', 64.0: 'Lanchkhuti', 65.0: 'Poti', 66.0: 'Martvili', 67.0: 'Abasha', 68.0: 'Martvili', 69.0: 'Senaki', 70.0: 'Khobi', 71.0: 'Zugdidi', 72.0: 'Chkhorotsku', 73.0: 'Tsalenjikha', 74.0: 'Batumi', 75.0: 'Kobuleti', 76.0: 'Khelvachauri', 77.0: 'Khulo', 78.0: 'Shuakhevi', 79.0: 'Khulo'}

None